---
- name: Add Elastic repo public signing key
  rpm_key:
      key: "{{logstash_gpgkey}}"
      state: present
  tags:
     - install

- name: Set LS Major Version Fact
  set_fact:
    _logstash_major_version: "{{ logstash_version | int }}"
  when: "{{ logstash_version | version_compare('5.0', '>=') }}"
  tags:
    - install

- name: Set yumrepo for LS > 5.x
  yum_repository:
    name: "logstash-{{ _logstash_major_version }}.x"
    description: "Logstash repository for {{ _logstash_major_version }}.x packages"
    baseurl: "{{ logstash_version_baseurl }}"
    gpgcheck: yes
    gpgkey: "{{ logstash_gpgkey }}"
    includepkgs: 'logstash'
    params:
      autorefresh: 1
      type: rpm-md
  when: logstash_version | version_compare('5.0', '>=')
  tags:
    - install

- name: Set yumrepo for LS < 5.x
  yum_repository:
    name: "logstash-{{ logstash_version }}"
    description: "Logstash repository for {{ logstash_version }}.x packages"
    baseurl: "http://packages.elastic.co/logstash/{{ logstash_version }}/centos"
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  when: logstash_version | version_compare('5.0', '<')
  tags:
    - install

- name: Install logstash
  yum:
    name: logstash
    update_cache: yes
    state: present
  tags:
     - install

